### ISSUE TITLE
Add dependency to aws-sdk

### ISSUE THREAD

**Issue by matsev** [hupe1980/cdk-multi-profile-plugin#12]
After starting a new project from scratch (using `cdk init`) and then adding the `cdl-multi-profile-plugin`), the `npx cdk deploy` command fails:

```bash
Unable to load cdk-multi-profile-plugin: Error: Cannot find module 'aws-sdk'
Require stack:
- /Users/user/Projects/cdk-test/node_modules/cdk-multi-profile-plugin/lib/ini-file-credential-provider-source.js
- /Users/user/Projects/cdk-test/node_modules/cdk-multi-profile-plugin/lib/multi-profile-plugin.js
- /Users/user/Projects/cdk-test/node_modules/cdk-multi-profile-plugin/lib/index.js
- /Users/user/Projects/cdk-test/node_modules/aws-cdk/lib/plugin.js
[capped]
```

Adding the `aws-sdk` as a dependency to the test project solves the problem, but since it is required by the `cdk-multi-profile-plugin` it could be added as a dependency to the plugin as well.

cdk-multi-profile-plugin version: 1.1.3

**Comment by vondeetzen** [comment]
Had the same issue today. 

@hupe1980 how about adding the dependency (would create a PR)? Or add the information to the documentation that aws-sdk has to be added to your local cdk project?

**Comment by hupe1980** [comment]
@vondeetzen Yes, I also encountered this issue. We should include the aws-sdk as a dependency. Would you like to create a PR?

**Comment by vondeetzen** [comment]
If cdk-multi-profile-plugin would provide aws-sdk as a transative dependcy to the runnable cdk project wouldn't it tie the aws-sdk version inside the cdk project? What happens when the aws-sdk of cdk-multi-profile-plugin is outdated or the runnable cdk project needs a newer / specific verison?

My suggestion is to add it as a peer dependency in order to ensure as much flexibility in the runnable cdk project as possible. With a peer dependency at least a hint is displayed to the user.

Are you okay with that?

**Comment by hupe1980** [comment]
The aws-sdk is already a peerDependency: https://github.com/hupe1980/cdk-multi-profile-plugin/blob/e99f7ad0e72eda172815cd0148436f317dc46018/cdk-multi-profile-plugin/package.json#L42-L45

We could clearly show it in the doc?
```bash
npm install cdk-multi-profile-plugin aws-sdk
```
How do you like that?
